### ISSUE TITLE
will tiup surpport deploy NFS?

### ISSUE THREAD

**Issue by FateTHarlaown** [pingcap/tiup#1057]
## Feature Request

**Is your feature request related to a problem? Please describe:**

the doc recomand user use  NFS to store the backup data, and it will be more convenient if tiup surpport deploy  NFS.
**Describe the feature you'd like:**

surppot NFS or can merge a pr that surpport it.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
I believe NFS should work with TiUP if you mount them on the remote before deploying a TiDB cluster. Is there any more specific feature you'd wish TiUP to support?

**Comment by FateTHarlaown** [comment]
> deploying

THX for you reply，What I mean is can we surpport deploy some compoments that maybe tidb needed, Like nfs and lvs.

**Comment by 9547** [comment]
> > deploying
> 
> THX for you reply，What I mean is can we surpport deploy some compoments that maybe tidb needed, Like nfs and lvs.

What you mean is to deploy or create NFS/LVS as a dependent component? IMO, it's not supported currently.

**Comment by AstroProfundis** [comment]
I still don't quite get your point...

 - If what you want is letting tiup to configure and mount NFS volumes, it not supported and we don't have any plan to do so;
 - If what you want is letting tiup to install NFS client utilities so that you can configure NFS manually, it not supported as we don't have support of any package management from distributions;
 - If what you want is using tiup to deploy a cluster on already mounted NFS volumes, it should be working but we haven't tested
