### ISSUE TITLE
Move related code to this repo

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#109]
Code for generating the manifests and server-side layouts should be part of this repository so that the two codebases can be kept in sync. If this work is done manually at the moment, then we should implement it in code :-)

**Comment by nrc** [comment]
I might not be the best person for this since I don't know what the related code is. :-)

Code that I'm aware of:

* tiup-cluster
* any playground code?
* any code for producing manifests and other server-side resources?

So, questions:

* is there benefit in adding tiup-cluster to the tiup repo, or are they better to keep separate?
* does code exist outside of this repo for the 2nd and 3rd items?
* is there any other TiUp code outside this repo?

**Comment by lonng** [comment]
I have proposed move tiup-cluster to the directory `tiup/components/cluster` several days ago, but the other people think we should keep the `tiup` codebase small and focus and component management instead of component implementation.

So I think we should keep other codebases outside this repo if them complex.

**Comment by nrc** [comment]
So, I propose we put all distribution and component management code here, and move other stuff to other repos.

So, move playground code to tiup-cluster, move client to its own repo, perhaps other components?

When we write code for producing manifests and making new releases, that code should live here.

**Comment by lonng** [comment]
1. We will write a new component `publish` to publish a community component to our registry (like cargo publish).  I think we should keep `package/publish` in the current repository because it is used to package a `tiup` component. 
2. Move the playground to `https://github.com/pingcap-incubator/tiup-cluster/tree/master/cmd`.
3. Other components move to its own repo.

Can we create a new organization and put all components into the organization?

**Comment by nrc** [comment]
> We will write a new component publish

I meant the code for us to publish TiDB, etc.

> Can we create a new organization and put all components into the organization?

sgtm

**Comment by lonng** [comment]
The organization tiup has been registered, we must pick an another name, how about tiup-ecosystem, do you have any advice?

**Comment by nrc** [comment]
tidb-tiup? or pingcap-tiup?

I would worry that tiup-ecosystem or similar names would be confused with the other tiup

**Comment by lonng** [comment]
I discussed with team members, we think the `pingcap-tiup` is a good candidate.

**Comment by lucklove** [comment]
We have put tiup-cluster into tiup/components/cluster and move the tiup repo to pingcap org.
