### ISSUE TITLE
The execution time of TiUP in different directories

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiup#1150]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

2. What did you expect to see?

3. What did you see instead?

tiup in General folder

```
mkdir /root/123
time tiup cluster display xxx

Total nodes: 63

real    0m1.304s
user    0m0.342s
sys     0m0.135s
```

tiup in git clone folder

```
Execute arbitrary command

git clone xxxx.git
cd xxx
time tiup cluster display xxx

Total nodes: 63

real    0m40.031s
user    0m1.416s
sys     0m0.877s

```

4. What version of TiUP are you using (`tiup --version`)?

```
v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460

```

**Comment by AstroProfundis** [comment]
With `git bisect` I can confirm this is introduced in #779 but I don't know why...

**Comment by AstroProfundis** [comment]
And... this happens before the `main()` of `tiup` itself, so it must be in the `init()` of some depends.

**Comment by AstroProfundis** [comment]
OK, it's invoked by `github.com/markbates/pkger`, which invokes `github.com/gobuffalo/here`, which used `go mod` to determine the current path of source.

The PR #779 imports `pkg/cluster/spec` in `cmd/mirror.go`, so that the `spec` package is initialized before `cmd/root.go`, which is the command root of `tiup`.

In `pkg/cluster/spec`, the first file in name order is `alertmanager.go` and it implements `InitConfig()`, so that `pkg/cluster/template/scripts` is imported, and then `pkg/cluster/embed` is imported, which imports and initializes `github.com/markbates/pkger`, and then the `go list` command is invoked.
