### ISSUE TITLE
Automatic cleaning

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#116]
TiUp uses various temporary and permanent directories. Some are removed automatically, others can be cleaned up using `tiup clean`. It would be nice if TiUp did more automatic tidying up.

**Comment by lucklove** [comment]
Emm... It seems the stuff need clean by `tiup clean` is because that the user run the component with `-T` flag: 
```
tiup -T <tag> component_name
```
In this case, the user's intention is to keep these data. And after this, the user may want to delete the data (they don't need it anymore), so `tiup clean` is needed. And in this case, we don't know when the user doesn't need these data, so automatic tidying up is impossible, I think.

**Comment by nrc** [comment]
In the case that the user doesn't use `-T`, we should ensure there is nothing left on disk that shouldn't be. It might be the case already, but we should check.

**Comment by lucklove** [comment]
> In the case that the user doesn't use -T, we should ensure there is nothing left on disk that shouldn't be.

Yes, we have done this. The only exception is that the cluster component will store data in `~/.tiup/storage`, which is designed to persistent data for a component like `cluster`
