### ISSUE TITLE
When tiup cluster failed to deploy or scale-out, need more hint to clarify why the operation failed

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiup#1330]
## Feature Request

**Is your feature request related to a problem? Please describe:**

e.g. # tiup cluster scale-out test-dumpling scale.toml
...
Error: failed to start pd: failed to start: pd 172.16.6.53:2379, please check the instance's log(/data0/tidb-deploy/pd-2379/log) for more detail.: timed out waiting for port 2379 to be started after 2m0s

Verbose debug logs has been written to /root/.tiup/logs/tiup-cluster-debug-2021-04-27-11-09-59.log.
Error: run `/root/.tiup/components/cluster/v1.4.0/tiup-cluster` (wd:/root/.tiup/data/SVkR1xc) failed: exit status 1

Then check /data0/tidb-deploy/pd-2379/log/* and  /root/.tiup/logs/tiup-cluster-debug-2021-04-27-11-09-59.log, there's not any helpful information to tell user the failed reason.
In this env, the reason is the diretory to save pd/cdc data not existed (which is defined in scale.toml).
One more exmaple is, when  executing "tiup cluster deploy xxx" failed to deploy the cluster, also no any specify hint for user why the cluster deploy failed, at last, user find the reson is cdc cannot find pd connection.

**Describe the feature you'd like:**

Add more failed information or hint when tiup operation failed.

**Why the featue is needed:**

This feature can save the time for user to debug the frequent failed scenario.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
That's because we don't have any detailed info of why the operation failed. The `cluster` command only get `stdout`, `stderr` and exit code from the SSH connection, if there's nothing useful in the standard outputs, there is nothing we can provide to the user.

That's why we print the hint to guide users to check log files of each components on the deployed server. If the log of a component itself does not contain enough information about how it fails to start / had to exit / crashed, it's better to ask the component to optimize its logging.

As for the reason you provided for this specific case:
> the reason is the diretory to save pd/cdc data not existed (which is defined in scale.toml).

Could you share us the content of `scale.toml` and the real file / dir layout on server the component fails to start?

**Comment by Tammyxia** [comment]
Sorry it's not the reason the diretory to save pd/cdc data not existed. The reason for the failed scale-out is not import for me now (since no any related log can be found to debug...)
Thanks for reply to this request, I will check the compont log if the compont failed to deploy or scale-out.

**Comment by AstroProfundis** [comment]
OK, the `cluster` component is supposed to create necessary directories on `scale-out` in most cases, so if the component fails to start due to path does not exist, that might be a bug of `tiup-cluster`.

I'm closing this issue for now, if it turns out not to be an issue of the component itself, please reopen it.
