### ISSUE TITLE
tiup tools HA

### ISSUE THREAD

**Issue by Auggie321** [pingcap/tiup#1439]
## General Question

Before asking a question, make sure you have:

- Searched existing Stack Overflow questions.
- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/pingcap/tiup/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [TiUP Readme](https://github.com/pingcap/tiup)
  - [TiUP Doc](https://github.com/pingcap/docs)

Questions from https://github.com/pingcap/docs-cn/issues/6479

Does tiup tools could alive in mutilple nodes at the same time in one tidb cluster?

Thanks

**Comment by 9547** [comment]
AFAIK, TiUP stores the cluster metadata locally, in the directory($HOME/.tiup). You can backup/share this directory to multiple hosts

**Comment by Auggie321** [comment]
@9547  thanks.
Use cronjob sync a1 tiup node .tidb dir data to b1(or more) per mins.
Official about tiup HA whether there is a better way, or is there, is that I missed it

**Comment by AstroProfundis** [comment]
As there is not daemon process in TiUP and builtin components as of now, all states are stored in the `$HOME/.tiup` directory (or whatever location `$TIUP_HOME` points to).

That's by design and intended to make it easy to backup everything by backing up the directory. So syncing the profile directory between two nodes are the correct way of doing "HA", another alternative would be using shared file systems such as NFS for the path.

**Comment by Auggie321** [comment]
@AstroProfundis thanks.
