### ISSUE TITLE
tiup cluster prune <cluster name> don't work

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiup#1684]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- scale-in two tikv, till they become Tomestone status.
- tiup cluster prune <cluster name>

2. What did you expect to see?
The two scaled-in TiKV disappeared in tiup cluster display <cluster name>

3. What did you see instead?

- The two scaled-in TiKV still visible in  tiup cluster display <cluster name>

- tiup cluster log in ~/.tiup/logs/tiup-cluster-debug-xxx.log has not any log about command "tiup cluster prune xxx"

4. What version of TiUP are you using (`tiup --version`)?

[root@localhost logs]# tiup --version
1.7.0 tiup
Go Version: go1.17.3
Git Ref: v1.7.0
GitHash: ce8eb0a645cc3ead96a44d67b1ecd5034d112cf0
[root@localhost logs]# tiup cluster --version
Starting component `cluster`: /root/.tiup/components/cluster/v1.8.0/tiup-cluster --version
tiup version 1.8.0 tiup
Go Version: go1.17.3
Git Ref: v1.8.0
GitHash: ff08d402711bca996c2b7d27f45ff4623ed794de

**Comment by AstroProfundis** [comment]
This seems a dupe w/ #1148 

If the scale-in operation was not fully finished (so that the `offline` mark in `meta.yaml` is not set), the `prune` command will not delete the node. We can optimize this behavior.

**Comment by AstroProfundis** [comment]
On OP's cluster, the `prune` is not working correctly even if the `offline: true` flag is manually added to `meta.yaml`, and that's because PD has [changed](https://github.com/tikv/pd/commit/951b2310ef983dea8516b9561598f23b065da2b2) their API response in nightly build, so that the `State` field is always 0 and be assumed as "Up".

We'll discuss with PD team about this potential compatibility breaking change.
