### ISSUE TITLE
Limit the use of tiup-cluster destroy

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1722]
two question：
1. we need three confirmation，clean data 、 clean log and want continue？
![image](https://user-images.githubusercontent.com/21033020/149111498-d361857e-73b4-4c38-b004-ec32aa2f7620.png)

2. @yiduoyunQ think，Do we need a switch to determine if destroy is enabled? The user's consideration is the influence of the command.Adding a layer of 'blocking' may allow customers to 'operate more accurately'

**Comment by yiduoyunQ** [comment]
## 

in my opinion, customer has 2 concerns:

- concern 1: `destroy` command is so convenient that it can clean all cluster data very quickly and we can not manually stop or recover it. So in customer's view the `destroy` command can not be treated as the same with other commands, but now they has the same double check like "Do you want to continue? [y/N]:(default=N)"

- concern 2: consider 2 situations below
  - situation 1: the cluster need to be destroyed is 'clusterA', customer mistake the name and want to destroy 'clusterB', finally 'clusterB' is destroyed
  - situation 2: the cluster need to be destroyed is 'clusterA', customer also want to destroy 'clusterA', but with human mistakes like misspell, finally 'clusterB' is destroyed.

We can not prevent situation1 from customer even we add more 'block' in this situation because customer mistake the origin name they want to destroy, but we may prevent situation2 from customer with some mechanism like a lock switch.

We can say that we already have a 'double check' mechanism so customer need check their command more carefully, and I also agree with it. But stand at customer's situation, maybe we can do more to prevent situation2 from our customer.

Disadvantage: add a new switch parameter should involve more steps in the destroy process, it will also bring more intellect overload to the customer, although we can disenable it by default but it will still bring a little more complexity if customer enable it and want to destroy the cluster.
