### ISSUE TITLE
TiKV config could be out-of-date

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/tiup#179]
I found that the sample `tikv.toml` generated by `writeTiKVConfig` is just hard coded in Tiup, which could be out-of-date (or even introducing some inconsistent issue of other components). Is there a workaround for this (e.g. pulling from upstream codebase by certain commit id)?

**Comment by lucklove** [comment]
This is only for the playground component, which is a local cluster bootstrapper. You can use --kv.config to override that.

**Comment by Fullstop000** [comment]
Overriding is always an alternative. But it could be better to always keep the default config up-to-date.

**Comment by lucklove** [comment]
> Overriding is always an alternative. But it could be better to always keep the default config up-to-date.

We only use a minimal config to make sure that tikv can bootstrap in the playground environment. The config used should be supported by all tikv versions.

Fetching config from the network is always deprecated because users can use [private mirror](https://pingcap.com/docs/stable/tiup/tiup-mirror/), where the network is unavailable.
