### ISSUE TITLE
Support canary upgrades via tiup

### ISSUE THREAD

**Issue by andreifedorov-bolt** [pingcap/tiup#2029]
As we run huge critical production systems on TiDB, we care a lot about the safety of upgrades. 
Currently, only full cluster upgrade is supported, however, we could benefit from the ability to upgrade only specific nodes in the cluster before doing the complete upgrade, to observe if there are no unexpected issues or performance degrade. 

Similar to reload/deploy commands, the option to limit by cluster roles or specific nodes could be added to upgrade command

**Comment by AstroProfundis** [comment]
The main reason we don't (yet) support partial upgrade of a TiDB cluster is that we are not able to make sure the compatibility of different versions of components in the cluster by code, so that a manual inspection is always needed during the whole upgrade progress in case anything went wrong.

At present, a possible workaround is to use the `patch` command to replace one or more nodes with a given binary, it will still be shown as the old version (with a `patched` flag) but actually running on whatever version you provided, and it will be then overwritten with a higher version on `upgrade`.

Meanwhile, the support of different versions of different components (and even different nodes) in one cluster is on our plan, we already have some initial works done, but I don't have any ETA for the whole thing yet.
