### ISSUE TITLE
TiUP does report error when using "-user“ in the command line and  "ser" is parsed as the user

### ISSUE THREAD

**Issue by fanfuxiaoran** [pingcap/tiup#850]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup cluster deploy tidb-te v4.0.0 ./test.yaml -user tidb     --skip-create-user
2. What did you expect to see?

I expect it reports error that I should use --user instead of -user

3. What did you see instead?

Error: Failed to initialize TiDB environment on remote host '****' (task.env_init.failed)
  caused by: Failed to create '~/.ssh' directory for user 'tidb'
    caused by: Failed to execute command over SSH for 'ser@***'
      caused by: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

4. What version of TiUP are you using (`tiup --version`)?
4.0.0

**Comment by lucklove** [comment]
I think we should better keep this behavior.  It's agreed by many cli libs that a single `-` should followed a single character and rest characters followed by that character will be it's param value whether there is a extra blank separator.

For example, the mysql client, has the same behavior with TiUP:
```sh
[root@localhost ~]# mysql -user -h127.0.0.1 -P 4000
ERROR 1045 (28000): Access denied for user 'ser'@'127.0.0.1' (using password: NO)
```

Closing this issue since there is no plan to fix it in TiUP. If it's a problem, we should fix it in https://github.com/spf13/cobra
