### ISSUE TITLE
TiUP destroy cluster ，ssh-key public residual

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiup#898]
## Feature Request

1. TiUP 删除 TiDB 集群后，目标机器中残留 cluster key 的公钥信息 ；是否可以清理掉？
2. TiUP deploy 部署时，在 + Generate SSH keys ... Done 步骤执行 ctrl + c ，再次部署时，目标机器会出现两条相同的 cluster key 公钥信息。

**Comment by 9547** [comment]
Good idea, sounds we need two features:

1. de-dup the same  public key;
2. add an argument to remove the public key or not(default is false). But how do you know that the key was added by tiup deploy and not by another user?

**Comment by lucklove** [comment]
> But how do you know that the key was added by tiup deploy and not by another user?

@9547 We can, TiUP will store generated key in ~/.tiup/storage/cluster/clusters/<cluster-name>/ssh，which is used by only that cluster. once destroyed, the public key added to remote is not useful anymore. Because of this, I think there is no need to add an argument to decide removing or not, just remove it, Or the argument's default value can be true

**Comment by lucklove** [comment]
> /close

@hi-rustin Can we have this command?
