### ISSUE TITLE
tiup dm deploy prometheus report error

### ISSUE THREAD

**Issue by WentaoJin** [pingcap/tiup#928]
![image](https://user-images.githubusercontent.com/34805682/99931269-da89c500-2d8e-11eb-8f86-86177d06ae8f.png)

![image](https://user-images.githubusercontent.com/34805682/99931278-e1183c80-2d8e-11eb-9087-ae4e702264ee.png)

It looks like the prometheus version in the tiup installation package should follow the tidb cluster version, and the dm is hard-coded,expect dm to have a separate prometheus version or merge the prometheus version

**Comment by lucklove** [comment]
Hi~ Thanks for your issue. 

### The problem
The surface reason of the problem is that you use the offline package for tiup-cluster to deploy a dm cluster (you should use one for tiup-dm instead), but the root cause of the problem is TiUP's poor offline package mechanism: you must choose the right offline package for what you want to deploy. this problem troubles us for a very long time.

For example, if you want to deploy tidb v4.0.0, you must choose the offline package for tidb v4.0.0, and if you want to deploy v4.0.1, you must choose the offline package for v4.0.1, otherwise, some packages may missing. What's worse, the dm use different version number with TiDB, so the dm cluster has it's own offline package.

### Alternative
Then can we use just one offline package to deploy anything? No, because if we do so, we must put every thing in one offline package and that's hundreds of gigabytes of data which is not acceptable

### Solution
However, the seprated and versioned offline package did cause pain, we must solve this. So we try another way: make it possible to merge two offline mirror: https://github.com/pingcap/tiup/pull/860

If you need deploy both tidb v4.0.0 and dm v2.0.0, you can download their offline packages and use the command `tiup mirror merge` to merge them to one package, then you can deploy both dm and tidb with just one package.

**Comment by lucklove** [comment]
Will release #860 in v1.3.0
