### ISSUE TITLE
Should keep grafana log dir consistent with other components

### ISSUE THREAD

**Issue by lucklove** [pingcap/tiup#999]
By default, the component will store logs in `{.DeployDir}/log` dir, however, grafana is an exception: https://github.com/pingcap/tiup/blob/master/templates/config/grafana.ini.tpl#L20

We should correct this by use `logs = {{.DeployDir}}/log` in the `grafana.ini.tpl`

**Comment by rkazak** [comment]
Has this already been fixed?

I see in the file,
https://github.com/pingcap/tiup/blob/1225c0123ae55beedc0b67a00ea8490226bad599/embed/templates/config/grafana.ini.tpl#L20

However under the process I see

```
grafana-s 3713 rkazak    3w      REG                1,4    737622          8639198643 /Users/rkazak/.tiup/data/SStQvD7/grafana/log/grafana.log
```

So is the issue here that `logs` in the template file is not being honored and we end up with `log` as the directory on the active system?

**Comment by lucklove** [comment]
> tiup/embed/templates/config/grafana.ini.tpl

Not yet, should be `logs = {{.DeployDir}}/log` instead of `logs = {{.DeployDir}}/logs`, because TiUP will create `{{.DeployDir}}/log` dir for each component. If it's `{{.DeployDir}}/logs`, grafana will use it's own log dir `{{.DeployDir}}/logs`. It's not consistent with other components.

**Comment by lucklove** [comment]
Do you have interest to fix this?

**Comment by rkazak** [comment]
Sure I can take a look at this.  What threw me was that according to the 'lsof' output it is as required? So did it get over-ridden somewhere along the way?

specifically in in test it was  => `/Users/rkazak/.tiup/data/SStQvD7/grafana/log/grafana.log`
